"""Français PS→6e. Sources : c1-2024 (domaine langage), fr-c2-2024, fr-c3-2025.
Repères d'âge du C1 : « avant 4 ans » → PS, « à partir de 4 ans » → MS, « à partir de 5 ans » → GS."""
from commun import E, S, F, D, ecrire

c1, c2, c3 = "c1-2024", "fr-c2-2024", "fr-c3-2025"

lecture = D("lecture", "Lecture",
    F("phonologie", "Conscience phonologique et principe alphabétique",
        E("PS MS GS", "notion", "Deux grandes acquisitions pour lire et écrire : la [[conscience phonologique]] (manipuler et isoler les unités sonores : syllabe, attaque, rime, [[phonème]]) et le [[principe alphabétique]] (lien lettres/sons). Progression : du mot à la [[syllabe]] puis au phonème ; séances courtes, structurées, répétées dès la PS.", c1, 13),
        E("PS", "competence", "Identifier les sons de la langue ; identifier un mot dans une phrase ; [[scander les syllabes]] d'un mot ; dire des comptines courtes à phonèmes proches.", c1, 13),
        E("PS", "exemple", "Frapper les syllabes de son prénom dans ses mains ; localiser la source d'un son familier.", c1, 13),
        E("MS", "competence", "+ Manipuler les syllabes d'un mot (ajout, suppression, permutation, répétition, fusion, substitution) ; entendre, discriminer des phonèmes ; à l'oral et sans support écrit, dénombrer et classer les mots selon leur nombre de syllabes.", c1, 14),
        E("GS", "competence", "+ Repérer et produire des [[rimes]] et des [[assonances]] ; entendre, discriminer, manipuler des phonèmes ; localiser un phonème dans un mot ; différencier les sons proches (on/en/un).", c1, 14),
        E("GS", "exemple", "Fusionner l'attaque de POISSON et la finale de SOURIS → pseudo-mot POIRIS ; trouver l'intrus à l'initiale : sac/Sacha/cartable.", c1, 14),
    ),
    F("lettres", "Connaître les lettres (nom, forme, son)",
        E("PS", "competence", "Reconnaître et nommer certaines lettres de son prénom écrit en [[capitales]].", c1, 13),
        E("MS", "competence", "+ Nommer les lettres de son prénom et de mots connus ; correspondance entre lettres scriptes majuscules/minuscules et [[cursives]] minuscules ; donner la valeur sonore de quelques lettres (voyelles).", c1, 14),
        E("GS", "attendu", "+ Connaître le [[nom des lettres]] de l'alphabet et leur [[valeur sonore]] (hormis les occlusives) ; connaître les trois graphies d'une lettre (capitale, script, cursive) ; distinguer les lettres visuellement proches (b/d, p/q) grâce à la cursive.", c1, 14),
    ),
    F("decodage", "Identifier les mots : décodage",
        E("CP CE1 CE2", "notion", "Trois entrées menées en parallèle : l'apprentissage puis l'automatisation du [[décodage]], la [[lecture à voix haute]], la [[compréhension]]. Enseigner les [[correspondances graphophonémiques (CGP)]] de façon systématique, intensive, structurée et quotidienne ; ne donner à lire que des textes [[déchiffrables]] (mots-outils réduits au minimum) ; faire écrire systématiquement les CGP étudiées.", c2, 4),
        E("CP", "repere", "Cadence soutenue : environ deux CGP par semaine. Manuel de lecture recommandé pour garantir la programmation des CGP.", c2, 5),
        E("CP", "attendu", "Fin période 1 : décoder et encoder 12 à 15 [[CGP]] régulières. Milieu d'année : 25 à 30 CGP ; prendre conscience des lettres finales muettes ; déchiffrer 15 à 30 mots/min. Fin d'année : [[30 mots par minute]] au minimum sans préparation, 50 après préparation.", c2, 5),
        E("CP", "exemple", "Automatiser la lecture de mots fréquents et transparents (le, la, ami, rire, lune) ; reconnaître des mots de même préfixe, radical ou suffixe.", c2, 5),
        E("CE1", "attendu", "+ Automatiser le décodage des CGP du CP ; en fin d'année, décoder toutes les CGP, y compris les plus complexes ; identifier directement les mots courants.", c2, 6),
        E("CE1", "exemple", "Lire des pseudo-mots (doir, stag, choust) ; lire « ils chantent » sans vocaliser les lettres muettes ; listes analogiques ça/glaçon/garçon (valeurs positionnelles de c, g, s).", c2, 6),
        E("CE2", "attendu", "+ Avoir automatisé toutes les CGP ; lire un texte nouveau par un décodage rapide ; utiliser la [[voie graphophonologique]] pour les mots inconnus sans perdre en fluidité.", c2, 7),
        E("CM1 CM2 6e", "notion", "La lecture vise toujours l'automatisation du déchiffrage ; mémoriser de plus en plus de mots fréquents et irréguliers (CM1).", c3, 4),
    ),
    F("fluence", "Lire à voix haute : fluence et expressivité",
        E("CP", "attendu", "[[Fluence]] : 30 mots/min sans préparation, 50 après préparation. Identifier la ponctuation sur un texte préparé ; amorcer une lecture expressive.", c2, 5),
        E("CE1", "attendu", "[[70 mots par minute]] ; respecter la ponctuation et les [[groupes de souffle]] ; lire de manière expressive.", c2, 6),
        E("CE2", "attendu", "[[90 mots par minute]] ; respecter ponctuation et [[liaisons]] ; lecture expressive manifestant la compréhension.", c2, 7),
        E("CE2", "exemple", "Lire une scène de théâtre en incarnant un personnage.", c2, 8),
        E("CM1", "attendu", "[[110 mots par minute]] ; lire sans effort un texte d'une page ; lire à voix haute, avec aisance et [[expressivité]], un texte court travaillé en amont ; gérer l'intensité de sa voix (volume, débit).", c3, 4),
        E("CM2", "attendu", "[[120 mots par minute]] ; texte long après préparation (ponctuation, liaisons, unités syntaxiques) ; travailler la [[mise en voix]] (intonation, effets).", c3, 4),
        E("6e", "attendu", "[[130 mots par minute]] ; [[phrasé]] et [[prosodie]] adaptés ; lire un texte de 10 à 20 lignes en regardant l'auditoire ; rendre émotions, intentions de l'auteur, dialogues.", c3, 5),
        E("CP CE1 CE2", "repere", "Chaque élève est évalué régulièrement en fluence (syllabes, mots, puis textes) ; le professeur mesure la vitesse de lecture pour constituer des groupes.", c2, 3),
    ),
    F("comprehension", "Comprendre un texte",
        E("PS MS GS", "notion", "Au moins une fois par jour, le professeur lit une histoire ou un texte documentaire et [[enseigne la compréhension]] : préparation en amont (contexte, lexique), questionnement ouvert puis précis (explicite et implicite), [[restitution]] variée (dessin, jeu théâtral, [[marottes]], reformulation), trace conservée.", c1, 16),
        E("PS", "competence", "Reconnaître et situer un personnage dans les illustrations ; comprendre des histoires liées à des expériences connues (le bain, le coucher).", c1, 17),
        E("MS", "competence", "+ Identifier personnage principal et secondaires ; histoires à [[structure répétitive]] ; commencer à comprendre l'[[implicite]] (émotions, sentiments).", c1, 17),
        E("MS", "exemple", "Raconter une histoire entendue plusieurs fois avec un support (marotte, boîte à histoires, tapis d'histoires).", c1, 17),
        E("GS", "competence", "+ Construire les caractéristiques des [[personnages archétypaux]] (loup, ogre, sorcière, fée…) ; comprendre émotions, intentions, sentiments ; relier lecture et expérience.", c1, 17),
        E("GS", "exemple", "Raconter une histoire connue dans son intégralité et sans support.", c1, 17),
        E("CP CE1 CE2", "notion", "Séances quotidiennes de compréhension sur des textes plus longs et résistants que ce que l'élève lit seul (lecture du professeur), puis dès la 3e période de CP sur des textes qu'il a lui-même décodés. Leviers : lexique, [[chaîne anaphorique]], [[inférences]], références culturelles ; [[justifier ses réponses par un retour au texte]].", c2, 4),
        E("CP", "attendu", "Dégager le sens global ; chaîne anaphorique ; [[inférences simples]] ; lire et comprendre seul un texte narratif, informatif ou prescriptif d'[[une dizaine de lignes]].", c2, 5),
        E("CP", "exemple", "Relier le lion / il / le fauve / le roi de la savane ; « J'ai pris mon parapluie » → le temps est pluvieux.", c2, 5),
        E("CE1", "attendu", "+ Stratégies pour élucider les mots inconnus ; résoudre des ambiguïtés ; texte d'[[une quinzaine de lignes]] ; donner un titre, résumer oralement.", c2, 6),
        E("CE2", "attendu", "+ Types narratif, informatif, prescriptif ; implicite appuyé sur indices et connaissances ; texte d'[[une vingtaine de lignes]] ; stratégies en cas de non-compréhension (relecture, dictionnaire…).", c2, 7),
        E("CM1", "competence", "[[Stratégies de compréhension]] ; repérer les informations [[explicites]] et pointer les informations implicites ; distinguer théâtre, poème, texte narratif.", c3, 4),
        E("CM2", "competence", "+ Textes plus longs et complexes ; restituer l'essentiel (explicite + implicite) ; reconnaître et nommer les principaux [[genres littéraires]].", c3, 4),
        E("6e", "competence", "+ Rattacher un texte à un genre ; inférences sur de larges extraits ; liens logiques, reprises nominales ; justifier ses interprétations.", c3, 5),
    ),
    F("documents", "Lire pour apprendre : supports et documents",
        E("PS", "competence", "Repérer les [[outils fonctionnels]] de la classe (étiquette du prénom, emploi du temps, affiches).", c1, 17),
        E("MS", "competence", "+ Identifier la fonction des écrits de la vie courante ; notion de [[destinataire]].", c1, 17),
        E("GS", "competence", "+ Différencier les [[types d'écrits]] ; repérer leur structure et leur mise en page (lettre, recette, conte, documentaire) ; vocabulaire : page, paragraphe, ligne, majuscule, ponctuation.", c1, 17),
        E("CM1", "competence", "Donner la [[nature et la source d'un document]] ; trouver des réponses dans des documents simples ; découvrir des [[documents composites]].", c3, 4),
        E("CM2", "competence", "+ Rapprocher deux documents convergents de genres différents ; prélever et combiner des informations (inférences).", c3, 4),
        E("6e", "competence", "+ Comparer des documents de genres différents ; interpréter une [[image fixe]].", c3, 5),
    ),
    F("lecteur", "Devenir lecteur : parcours et culture littéraire",
        E("PS MS GS", "notion", "Initier un [[parcours de lecteur]] : chaque jour, un temps de lecture offerte sans questionnement pour le plaisir ; textes patrimoniaux (contes, légendes, fables, poèmes), littérature de jeunesse, recettes, documentaires.", c1, 16),
        E("CP CE1 CE2", "repere", "Lire [[5 à 10 œuvres]] complètes par an (patrimoine et littérature de jeunesse) ; mise en réseau ; carnet de lecture ; fréquenter les lieux de lecture (BCD, médiathèque).", c2, 4),
        E("CP CE1 CE2", "exemple", "Lectures fondatrices : contes d'Andersen, d'Aulnoy, Grimm, Leprince de Beaumont, Perrault ; Dickens, Carroll ; fables de La Fontaine ; récits adaptés de la mythologie.", c2, 4),
        E("CM1", "repere", "[[Au moins sept œuvres complètes]] par an au cours moyen : en CM1, 2 œuvres du patrimoine et 5 de littérature de jeunesse.", c3, 3),
        E("CM2", "repere", "3 œuvres du patrimoine et 4 de littérature de jeunesse.", c3, 4),
        E("CM1 CM2", "notion", "Perspective « [[Découvrir – Jouer]] ». Six [[entrées littéraires]] (ordre libre) : découvrir des héroïnes, des héros ; se confronter au merveilleux, à l'étrange ; imaginer et vivre d'autres vies ; comprendre et interroger la morale ; savourer le goût des mots (poésie) ; se découvrir, s'affirmer dans le rapport aux autres.", c3, 6),
        E("6e", "repere", "Au moins 6 œuvres : 3 du patrimoine en [[lecture intégrale]] + 3 en [[lecture cursive]] ; groupements de textes.", c3, 5),
        E("6e", "notion", "Cinq entrées prescrites, traitées en [[projets d'apprentissage]] : récits des origines ; poésie (mots et merveilles) ; théâtre (ruses en action) ; partir à l'aventure ; rencontrer des monstres.", c3, 7),
    ),
)

ecriture = D("ecriture", "Écriture",
    F("geste", "Geste d'écriture et écriture cursive",
        E("PS MS GS", "notion", "Distinguer entraînement au geste moteur ([[graphisme]]), geste d'écriture et production d'écrit. Posture, coordination des quatre articulations (épaule, coude, poignet, doigts), coordination œil-main. Cursive introduite en MS ou quand l'enfant est prêt.", c1, 18),
        E("PS", "competence", "Motricité fine, graphismes ; guider son geste par le regard ; formes de base (traits, points, boucles, cercles).", c1, 18),
        E("MS", "competence", "+ Posture et [[préhension]] correctes ; tracer les lettres capitales ; s'initier aux tracés de la cursive.", c1, 19),
        E("GS", "attendu", "+ Tenir son stylo par la [[pince des doigts]] ; travailler la [[ligature]] ; tracer et enchaîner les lettres cursives ; écrire son prénom sans modèle.", c1, 19),
        E("CP", "competence", "Écrire en cursive tous les graphèmes étudiés en décodage et les enchaîner (syllabes, mots, phrases).", c2, 9),
        E("CE1", "competence", "+ Automatiser les minuscules cursives ; 2e partie d'année : tracé des [[majuscules cursives]] par familles de gestes.", c2, 11),
        E("CE2", "attendu", "Automatiser minuscules et majuscules cursives.", c2, 12),
        E("CM1 CM2 6e", "notion", "Le geste n'est pas encore automatisé (il se conquiert au cycle 4) : entraînement régulier, copie ; écrire aussi sur supports numériques, mais la maîtrise du geste cursif reste importante.", c3, 8),
    ),
    F("copie", "Copie",
        E("CP", "attendu", "Dès la fin de la période 1 : copier une phrase ; verbaliser des [[stratégies de copie]] (prise d'indices, mémorisation) ; fin d'année : 3 ou 4 phrases sans erreur.", c2, 10),
        E("CE1", "attendu", "+ 4 à 5 phrases (période 1), 5 ou 6 lignes (période 3), une dizaine de lignes en fin d'année ; comparer l'efficacité des stratégies.", c2, 11),
        E("CE2", "attendu", "+ Dizaine de lignes sans erreur, vitesse et exactitude, mises en page complexes.", c2, 12),
        E("CM1 CM2", "competence", "Copier et produire des textes ; acquérir des stratégies de copie.", c3, 9),
        E("6e", "competence", "Copier de façon lisible, régulière, soignée, sans erreur d'orthographe ou de ponctuation.", c3, 10),
    ),
    F("encodage", "Encoder, écrire sous dictée",
        E("MS GS", "competence", "Essais d'écriture et [[encodage]] de mots [[transparents]] (sans double consonne ni lettre muette), quotidiens dès la MS ; en GS, encodage en lien avec les lettres et la conscience phonologique.", c1, 19),
        E("CP", "competence", "Encoder des syllabes puis des mots selon la progression des CGP ; dès la fin de la 2e période, mots avec lettres muettes apprises ; fin d'année : [[dictée]] de mots et de phrases.", c2, 9),
        E("CE1", "competence", "+ Mots fréquents réguliers puis irréguliers ; accords dans le GN et marque -nt.", c2, 11),
        E("CE2", "competence", "+ Phonèmes à plusieurs graphies (/o/, /é/, /an/, /s/…) ; chaînes d'accord dans la phrase.", c2, 12),
        E("CP CE1 CE2", "notion", "La dictée est d'abord une activité d'écriture (principe alphabétique, encodage), avant d'être un outil d'évaluation ; l'erreur est source de progrès.", c2, 9),
    ),
    F("production", "Produire des écrits",
        E("PS MS GS", "notion", "[[Dictée à l'adulte]] dès la PS (toutes les semaines, en petits groupes) : définir l'intention d'écriture, préparer, énoncer, dicter, réviser.", c1, 19),
        E("PS", "competence", "Percevoir que l'[[écrit encode l'oral]] ; tracer volontairement des signes abstraits qui ne sont pas des dessins.", c1, 20),
        E("MS", "competence", "+ Comprendre que l'écrit code des sons ; proposer le contenu d'un message en dictée à l'adulte ; sens de lecture gauche-droite, haut-bas ; écrire un mot transparent avec modèle.", c1, 20),
        E("GS", "competence", "+ Segmenter l'oral (mots, syllabes, phonèmes) ; réinvestir le principe alphabétique pour produire un écrit ; comprendre qu'il existe une [[norme]] (ponctuation, majuscules) ; persévérer : préparation, énonciation, révision.", c1, 20),
        E("CP CE1 CE2", "notion", "Méthodologie : [[planification]], mise en mots avec vigilance orthographique, [[révision]]. Écrits collaboratifs dès le CP ; écrits longs de plus en plus autonomes au fil du cycle.", c2, 10),
        E("CP", "attendu", "Écrits courts de [[une à cinq lignes]] ; majuscule et ponctuation finale forte.", c2, 10),
        E("CP", "exemple", "Écrire un nouvel épisode d'un récit à structure répétitive ; « J'ai un chat. / J'ai un… ».", c2, 10),
        E("CE1", "attendu", "+ Connecteurs ; brouillons ; fin d'année : texte de [[six ou sept phrases]] cohérent.", c2, 11),
        E("CE2", "attendu", "+ Texte d'[[une dizaine de lignes]] de différents types ; connecteurs temporels et logiques ; relecture méthodique.", c2, 12),
        E("CM1 CM2 6e", "notion", "Écrits courts (une à cinq phrases) et longs ; [[brouillon]] systématique ; réécriture ; projets d'écriture créative ; normalisation centrée sur l'accord dans le GN, l'accord sujet-verbe et l'attribut du sujet.", c3, 8),
        E("CM1", "competence", "Situations d'écriture : [[raconter, expliquer]] ; cohérence textuelle ; améliorer son texte avec l'enseignant et les pairs.", c3, 9),
        E("CM2", "competence", "+ [[Décrire, dialoguer]] ; appliquer la cohérence textuelle ; autoévaluation.", c3, 9),
        E("6e", "competence", "+ [[Résumer, synthétiser]] ; argumenter et justifier ; hiérarchiser des idées.", c3, 10),
    ),
    F("ecrire-apprendre", "Écrire pour réfléchir et apprendre",
        E("CM1", "competence", "Écrits de travail : repérer et trier l'information ; écrits réflexifs courts (point de vue) ; reformuler l'essentiel d'une leçon.", c3, 9),
        E("CM2", "competence", "+ Comparer deux documents ; reformuler une leçon de manière schématique.", c3, 9),
        E("6e", "competence", "+ Résumer, synthétiser ; s'approprier seul l'essentiel d'une leçon.", c3, 10),
    ),
)

oral = D("oral", "Oral",
    F("syntaxe-orale", "Syntaxe orale (maternelle)",
        E("PS", "competence", "Pronoms il/elle puis je ; présent puis système à trois temps (présent / passé composé / futur proche) ; premiers connecteurs et/et puis.", c1, 9),
        E("MS", "competence", "+ Pronoms tu, on ; imparfait, passé composé, [[conditionnel]] ; connecteurs temporels et spatiaux ; subordination (parce que, que, qui).", c1, 9),
        E("GS", "competence", "+ Nous, vous ; imparfait / plus-que-parfait ; [[futur simple]], futur antérieur ; [[introducteurs de complexité]] (où, quand, pour que, si, comme).", c1, 10),
    ),
    F("articuler", "Articuler distinctement (maternelle)",
        E("PS", "competence", "Articuler les couples de consonnes proches t/k, f/s, m/n.", c1, 11),
        E("MS", "competence", "+ Nasales é/in, a/an, o/on ; f/v, s/z, p/b, t/d, k/g.", c1, 11),
        E("GS", "attendu", "+ ch/s, ch/j, ch/z ; doubles consonnes br/cr/bl/pl. En fin de maternelle : prononcer les [[trente-six phonèmes]] du français.", c1, 11),
    ),
    F("ecouter", "Écouter pour comprendre",
        E("CP", "competence", "Comprendre un message de quelques minutes et mémoriser les informations importantes ; réaliser une consigne, une recette, une règle du jeu.", c2, 13),
        E("CE1", "competence", "+ [[Attention active]] pour repérer, classer, ordonner les informations.", c2, 14),
        E("CE2", "competence", "+ Relier plusieurs informations d'un message de plus en plus long (5 minutes maximum).", c2, 15),
        E("CM1 CM2 6e", "competence", "Posture d'auditeur : [[écoute active]] orientée par un but ; comprendre un message d'un média (interview, reportage) ; identifier les genres de discours.", c3, 11),
    ),
    F("dire", "Dire pour être compris : produire des discours",
        E("PS", "competence", "Entrer en communication ; dire ce qu'on fait, ce qu'on a fait ; oraliser collectivement un texte mémorisé.", c1, 12),
        E("MS", "competence", "+ Dire ce qu'on va faire et comment ; oraliser un court texte mémorisé.", c1, 12),
        E("GS", "competence", "+ [[Langage d'évocation]] : se faire comprendre d'un adulte qui ne connaît pas la situation ; émettre une hypothèse.", c1, 12),
        E("MS GS", "repere", "Mémorisation d'un texte par semaine (chants, comptines, poésies).", c1, 12),
        E("CP CE1 CE2", "repere", "Une dizaine de [[poèmes]] mémorisés par an ; séances quotidiennes d'oral ; trois activités : comprendre, parler en continu, parler en interaction.", c2, 13),
        E("CP", "competence", "Brève production orale pour rapporter, raconter, décrire, expliquer ; oraliser un texte mémorisé.", c2, 14),
        E("CE1", "competence", "+ Utiliser tous les temps verbaux ; évaluer sa prestation selon des critères.", c2, 14),
        E("CE2", "competence", "+ Argumenter, justifier ; exposé de quelques minutes ; expliquer un raisonnement en maths ou en sciences.", c2, 15),
        E("CM1 CM2 6e", "competence", "Production orale claire et organisée pour raconter, expliquer, [[argumenter]], justifier ; lecture expressive devant un public ; [[l'oral comme outil réflexif]].", c3, 11),
    ),
    F("echanges", "Participer à des échanges",
        E("CP", "competence", "Respecter les règles d'échange ; prendre conscience des [[niveaux de langue]].", c2, 14),
        E("CE1", "competence", "+ Adapter le [[registre de langue]] (familier, courant, soutenu).", c2, 14),
        E("CE2", "competence", "+ Tenir compte de ce qui a été dit ; jeux de rôles.", c2, 15),
        E("CM1 CM2 6e", "competence", "Codes de la communication ; construire une analyse collective en interaction ; porter un [[regard critique sur l'oral produit]] ; débattre.", c3, 11),
    ),
)

vocabulaire = D("vocabulaire", "Vocabulaire",
    F("enrichir", "Enrichir son vocabulaire",
        E("PS MS GS", "notion", "[[L'enseignement du vocabulaire est prioritaire]] à l'école maternelle : explicite, progressif et structuré ; [[2 500 mots]] en fin de GS. Quatre étapes : apporter des mots nouveaux, structurer le lexique, faire mémoriser, réutiliser. [[Réseaux lexicaux]] (verbes, noms, adjectifs, mots grammaticaux, expressions).", c1, 8),
        E("PS MS", "repere", "[[Deux corpus]] de mots par période.", c1, 8),
        E("GS", "repere", "Trois corpus par période.", c1, 9),
        E("CP", "repere", "[[Quatre corpus]] par période.", c2, 16),
        E("CE1", "repere", "Cinq corpus par période.", c2, 16),
        E("CE2", "repere", "Six corpus par période.", c2, 16),
        E("CP CE1 CE2", "notion", "Enseignement quotidien, en séances dédiées ; passer d'un [[savoir passif]] à un [[savoir actif]] ; privilégier mots fréquents et termes [[polysémiques]].", c2, 15),
        E("CM1 CM2 6e", "notion", "Trois étapes : rencontre en contexte, étude systématique (structuration, catégorisation), réemploi surtout à l'écrit ; vocabulaire des disciplines ; outil personnel de collecte ; [[listes de fréquence]].", c3, 13),
        E("6e", "competence", "Choisir seul la stratégie pour comprendre un mot inconnu (déduire, vérifier, rechercher) ; [[étymologie]].", c3, 15),
    ),
    F("relations", "Relations entre les mots",
        E("PS", "competence", "Organiser les mots en [[catégories]] ; trouver un intrus.", c1, 8),
        E("MS", "competence", "+ Mots polysémiques ; synonymes ; comprendre un mot nouveau par un mot connu (animal/animalerie).", c1, 9),
        E("GS", "competence", "+ Sens propre / [[sens figuré]] et [[dérivations]] (sans que ces notions soient enseignées) ; [[hyperonymes]] ; inférer le sens d'un mot.", c1, 9),
        E("GS", "exemple", "Dévorer un gâteau / dévorer un livre ; arroser → arrosage ; véhicule, hyperonyme de voiture, bus, vélo.", c1, 9),
        E("CP", "competence", "Répertoires par thème, classe, famille, analogie morphologique ; [[champ lexical]] ; [[synonymes]] et [[antonymes]] ; sens des principaux affixes (dé-, re-, in-, -eur…).", c2, 16),
        E("CE1", "competence", "+ Hiérarchiser termes génériques et spécifiques ; niveaux de langue ; sens propre / figuré ; trier les dérivés selon [[préfixes]] et [[suffixes]].", c2, 17),
        E("CE1", "exemple", "Aliment > laitage > fromage > gruyère ; avoir une peur bleue, prendre ses jambes à son cou.", c2, 17),
        E("CE2", "competence", "+ Gradation (crainte > peur > épouvante) ; dérivations et classe grammaticale (observation, observer, observable).", c2, 18),
        E("CM1 CM2", "competence", "Relations morphologiques et sémantiques ; synonymie, antonymie ; polysémie dans un contexte non référentiel (CM2).", c3, 14),
        E("6e", "competence", "+ Mots [[simples, dérivés et composés]] ; composer et décomposer des mots.", c3, 15),
    ),
    F("orthographe-lexicale", "Orthographe lexicale",
        E("CP", "competence", "Mots réguliers fréquents ; accents ; valeur de s, c, g ; m devant m, b, p ; lettre muette finale expliquée par un mot de la famille (chat/chaton).", c2, 17),
        E("CE1", "competence", "+ Mots irréguliers fréquents ; mots invariables ; anticiper une lettre muette finale (blanc/blanche).", c2, 18),
        E("CE2", "competence", "+ Raisonnement morphologique (radical, préfixe, suffixe) : beau → beauté.", c2, 19),
        E("CM1 CM2 6e", "competence", "Écrire correctement les mots fréquents en s'appuyant sur les régularités et la formation des mots ; en 6e, en situation autonome.", c3, 14),
    ),
)

grammaire = D("grammaire", "Grammaire et orthographe",
    F("phrase", "La phrase : types et formes",
        E("CP", "competence", "Notion de [[phrase]] et ses trois marqueurs (majuscule, ponctuation forte, sens) ; trois [[types de phrases]] (déclarative, interrogative, impérative) ; formes [[négative]] et [[exclamative]].", c2, 20),
        E("CE1", "competence", "+ Reconnaître et utiliser les types ; effectuer des transformations.", c2, 21),
        E("CE2", "competence", "+ Produire les types et formes ; [[discours rapporté]] (guillemets).", c2, 22),
        E("CM1", "competence", "+ Comprendre leurs effets dans un texte ; réalisations du type interrogatif (inversion, est-ce que, intonation).", c3, 17),
        E("CM2 6e", "competence", "Consolider sur des corpus plus complexes.", c3, 18),
    ),
    F("constituants", "Constituants de la phrase simple",
        E("CP CE1 CE2", "notion", "Deux constituants obligatoires : [[groupe sujet (GS)]] et [[groupe verbal]] (verbe + compléments du verbe : COD, COI, attribut), reconnus sans distinguer les compléments entre eux. Les compléments circonstanciels sont réservés au cycle 3.", c2, 19),
        E("CE1", "exemple", "[[Manipulations]] : La maîtresse raconte une histoire aux enfants → Elle la raconte aux enfants (substitution) ; Tous les jours, elle mange à la cantine (déplacement).", c2, 21),
        E("CM1", "competence", "Types de sujets ; distinguer [[complément d'objet]] et [[complément circonstanciel]] (repéré, facultatif) ; COD / COI dans des phrases prototypiques ; manipulations : déplacement, suppression, substitution, addition, encadrement.", c3, 17),
        E("CM2", "competence", "+ [[Sujet inversé]] ; [[attribut du sujet]] ; CC de temps, de lieu, de cause.", c3, 19),
        E("6e", "competence", "+ Tous les constituants ; opposer attribut du sujet et COD ; construction du verbe.", c3, 20),
    ),
    F("classes", "Classes de mots (nature) et fonctions",
        E("CP", "competence", "Constituer des corpus par classe : noms, verbes, déterminants, adjectifs, pronoms personnels.", c2, 20),
        E("CE1", "competence", "+ Nommer : déterminant, nom commun, [[nom propre]], adjectif, verbe, pronom personnel sujet.", c2, 21),
        E("CE2", "competence", "+ [[Adverbe]] ; mots variables / invariables.", c2, 22),
        E("CM1", "competence", "+ Notions de [[nature]] et [[fonction]] ; déterminants (articles définis, indéfinis, possessifs, démonstratifs) ; conjonctions de coordination ; pronoms personnels sujets / compléments.", c3, 17),
        E("CM2", "competence", "+ [[Prépositions]] ; [[conjonctions de subordination]].", c3, 19),
        E("6e", "competence", "+ Fonction des pronoms personnels ; lien pronom-[[antécédent]].", c3, 20),
        E("CM1 CM2 6e", "repere", "Terminologie : nature/fonction ; sujet, COD, COI, attribut du sujet, complément circonstanciel, complément du nom, épithète ; proposition, juxtaposition, coordination, subordination.", c3, 16),
    ),
    F("groupe-nominal", "Groupe nominal et chaîne d'accords",
        E("CP", "competence", "Masculin/féminin, singulier/pluriel ; se familiariser avec la [[chaîne d'accords]] (déterminant/nom/adjectif).", c2, 20),
        E("CP", "exemple", "un petit garçon → une petite fille ; une olive / des olives.", c2, 20),
        E("CE1", "competence", "+ Reconnaître le [[GN]] ; marques -s et -e.", c2, 21),
        E("CE2", "competence", "+ Pluriels irréguliers (-x, -al/-aux) ; féminins audibles (lecteur/lectrice).", c2, 22),
        E("CM1", "competence", "+ [[Nom noyau]] (donneur d'accord) ; Dét. + Nom (+ Adj.) ; notion d'[[épithète]] ; systématiser la chaîne d'accords.", c3, 18),
        E("CM2", "competence", "+ Expansion du nom ; [[complément du nom]] ; épithète / attribut.", c3, 19),
        E("6e", "competence", "+ Adjectif épithète vs GN prépositionnel complément du nom.", c3, 20),
    ),
    F("accord-sujet-verbe", "Accord sujet-verbe",
        E("CP", "competence", "S'initier à la relation sujet-verbe par le sens et les transformations.", c2, 20),
        E("CP", "exemple", "La voiture roule → Les voitures roulent ; nous → -ons, vous → -ez, ils → -ent.", c2, 20),
        E("CE1 CE2", "competence", "Identifier la relation sujet-verbe par les transformations de temps et de personne.", c2, 21),
        E("CM1", "competence", "+ Nom noyau du sujet ; accord du [[participe passé]] avec [[être]] ; distinguer variations du verbe et du nom (il élève / une élève).", c3, 18),
        E("CM2", "competence", "+ Sujets inversés ; chaîne sujet / attribut ; participe passé avec [[avoir]] : accord avec le [[COD]] (pronom personnel antéposé).", c3, 19),
        E("6e", "competence", "Raisonner sur l'accord sujet/verbe ; maîtriser les accords du participe passé.", c3, 20),
    ),
    F("conjugaison", "Conjugaison",
        E("CP", "competence", "Être et avoir au [[présent]] ; observer les formes verbales fréquentes.", c2, 20),
        E("CE1", "competence", "Présent, [[imparfait]], [[futur]], [[passé composé]] : être, avoir, 1er groupe ; [[radical]] et [[terminaison]] ; trouver l'infinitif.", c2, 21),
        E("CE2", "competence", "+ Verbes irréguliers du 3e groupe : faire, aller, dire, venir, pouvoir, voir, vouloir, prendre.", c2, 22),
        E("CM1", "competence", "+ 2e groupe ; [[marque de temps]] et [[marque de personne]] (imparfait -ai-/-i-, futur -r-) ; passé composé = auxiliaire + participe passé ; radicaux variables du 1er groupe (-yer, -eler, -cer, -ger…).", c3, 18),
        E("CM2", "competence", "+ [[Passé simple]] et [[plus-que-parfait]].", c3, 19),
        E("6e", "competence", "+ [[Impératif présent]] et [[conditionnel présent]] ; initiation aux [[valeurs des temps]] (temps chronologique vs temps verbal).", c3, 21),
    ),
    F("phrase-complexe", "Phrase complexe",
        E("CM2", "competence", "Distinguer [[phrase simple]] et [[phrase complexe]] en repérant les verbes conjugués.", c3, 19),
        E("6e", "competence", "+ Notion de [[proposition]] ; [[juxtaposition]], [[coordination]], [[subordination]].", c3, 20),
    ),
)

ecrire({
    "id": "francais",
    "nom": "Français",
    "nomMaternelle": "Le développement et la structuration du langage oral et écrit",
    "intentions": "Maternelle : compréhension et usage du langage ; [[vocabulaire]] prioritaire ; passage progressif de l'oral à l'écrit. Cycle 2 : construire les fondements de la langue ; [[apprendre à lire]] est l'objectif central ; cinq [[activités langagières]] : comprendre un énoncé oral, parler en continu, parler en interaction, écrire, lire ; 10 h hebdomadaires. Cycle 3 : viser l'[[autonomie]] ; la [[compréhension]] est l'objectif central ; perspective « Découvrir – Jouer ».",
    "domaines": [lecture, ecriture, oral, vocabulaire, grammaire],
})
