"""Mathématiques PS→6e. Sources : c1-2024 (domaine « L'acquisition des premiers outils mathématiques »),
maths-c2-2024, maths-c3-2025 et exemples Éduscol C3 (maths-ex-*).
Repères d'âge du C1 : « avant 4 ans » → PS, « à partir de 4 ans » → MS, « à partir de 5 ans » → GS."""
from commun import E, S, F, D, ecrire

c1, c2, c3 = "c1-2024", "maths-c2-2024", "maths-c3-2025"
x4, x5, x6 = "maths-ex-cm1", "maths-ex-cm2", "maths-ex-6e"

nombres = D("nombres", "Nombres",
    F("quantites", "Construire le nombre : quantités (maternelle)",
        E("PS MS GS", "notion", "Objectifs de [[cardinalité]] : comprendre que tout nombre s'obtient en ajoutant un au précédent ; qu'une quantité ne dépend ni de la nature ni de la position des objets ; associer quantité, nom et écriture chiffrée ; dénombrer, comparer, [[composer et décomposer]] ; installer le [[principe de cardinalité]] (éviter le numérotage). Écriture chiffrée seulement après le sens en termes de quantité. Ne pas introduire prématurément le zéro.", c1, 37),
        E("PS", "attendu", "Dénombrer jusqu'à trois, voire quatre ; [[comparer par correspondance terme à terme]] ; compositions « un et un font deux » ; [[comptine numérique]] de un à six.", c1, 38),
        E("PS", "exemple", "Situation du voyageur : aller chercher juste ce qu'il faut de voyageurs pour occuper chaque siège (d'abord sans limiter les trajets, puis en un seul trajet).", c1, 38),
        E("MS", "attendu", "+ Jusqu'à six ; parcourir une collection en passant une et une seule fois par chaque élément ([[énumération]]) ; écrire les nombres de un à six ; comptine jusqu'à douze.", c1, 39),
        E("MS", "exemple", "Boîte de douze œufs percée de fentes : mettre un jeton et un seul dans chaque alvéole ; aller chercher en un seul trajet autant de verres que d'assiettes.", c1, 39),
        E("GS", "attendu", "+ Jusqu'à dix, voire au-delà ; un de plus / un de moins ; [[surcompter]] ; compositions et décompositions jusqu'à dix, dont les [[doubles]] ; écrire en chiffres de un à dix ; comptine jusqu'à trente, à rebours de dix à un, de deux en deux.", c1, 41),
        E("GS", "exemple", "Huit objets en deux constellations de quatre : compter un à un, « mettre quatre dans sa tête » et surcompter, ou dire « quatre et quatre font huit ».", c1, 41),
    ),
    F("rang", "Rang et position : nombre ordinal",
        E("MS", "competence", "Comprendre la notion de [[rang]] (jusqu'à six) ; déterminer l'effet d'un déplacement sur une position ; se familiariser avec la [[bande numérique]].", c1, 43),
        E("GS", "competence", "+ Rang jusqu'à dix, en changeant le point de départ ou le sens de parcours ; lien entre un ajout et un avancement ; construire la bande numérique jusqu'à dix.", c1, 43),
        E("MS GS", "notion", "La conception spatiale du nombre (jeu de l'oie, bande numérique) préfigure la ligne numérique ; l'enseignant emploie les ordinaux, l'élève peut dire « si je suis sur le quatre et que j'avance de deux, je me retrouve sur le six ».", c1, 42),
        E("CP", "competence", "Nombres [[ordinaux]] jusqu'à « vingtième » ; lien entre le rang et le nombre d'éléments qui précèdent ; suites de symboles.", c2, 4),
        E("CE1", "competence", "+ Ordinaux jusqu'à cent ; [[suite évolutive]] (1, 2, 4, 7, 11, 16…).", c2, 11),
    ),
    F("entiers", "Nombres entiers : numération",
        E("CP CE1 CE2", "notion", "[[Aspect décimal]] (base dix) et [[aspect positionnel]] dès la période 1 du CP ; collections organisées en groupes de dix ; matériel : cubes emboîtables, bûchettes, [[matériel multibase]], monnaie fictive ; diverses représentations d'un nombre (matériel, chiffres, oral, [[unités de numération]], décomposition, lettres) ; placer des nombres sur une [[demi-droite graduée]].", c2, 3),
        E("CP", "attendu", "Nombres jusqu'à [[cent]] (59 au plus tard en période 2, 100 en période 3) ; écriture en lettres jusqu'à cinquante.", c2, 3),
        E("CP", "exemple", "Expliquer pourquoi 23 n'est pas le même nombre que 32.", c2, 4),
        E("CE1", "attendu", "Nombres jusqu'à [[mille]] ; la centaine dès la période 1 ; relations unités / dizaines / centaines.", c2, 10),
        E("CE1", "exemple", "235 timbres vendus par plaques de cent, carnets de dix ou à l'unité : proposer quatre commandes.", c2, 11),
        E("CE2", "attendu", "Nombres jusqu'à 10 000 ; décomposition (4 × 1 000) + (6 × 100) + (3 × 10) + (5 × 1).", c2, 19),
        E("CM1", "attendu", "Jusqu'à [[999 999]] (5-6 chiffres à partir de la période 3 ou 4 seulement) ; multiples de 2, 5 et 10 ; seuls les [[critères de divisibilité]] par 2, 5 et 10 sont au programme.", c3, 5),
        E("CM2", "attendu", "Jusqu'à 999 999 999 ; [[diviseurs]] et [[multiples]] communs (nombres ≤ 30, < 15).", c3, 9),
        E("6e", "attendu", "Le [[milliard]] ; valeur des chiffres selon leur rang (jusqu'au millième).", c3, 13),
    ),
    F("fractions", "Fractions",
        E("CE1", "competence", "[[Fractions d'un tout]] (≤ 1), dès la période 2 : [[fractions unitaires]] puis non unitaires ; « moitié », « demi », « quart » ; dénominateurs 2, 3, 4, 5, 6, 8, 10 ; [[numérateur]], [[dénominateur]] ; comparer (même dénominateur, numérateur 1) ; additionner et soustraire (même dénominateur).", c2, 12),
        E("CE1", "exemple", "Comprendre, par manipulation, que 1/3 est supérieur à 1/6, ce qui peut être contre-intuitif (3 < 6).", c2, 12),
        E("CE2", "competence", "+ Égalités de fractions (5/10 = 1/2) ; dénominateur ≤ 12 ; à partir de la période 3, graduer une [[bande-unité]] en fractions d'unité : la fraction acquiert un statut de nombre ; mesurer des longueurs non entières.", c2, 20),
        E("CM1", "competence", "+ Fractions supérieures à 1 ; entier + fraction ; encadrer entre deux entiers ; placer sur une demi-droite graduée ; fraction [[opérateur]] (un tiers de 12 billes) ; dénominateur ≤ 20.", c3, 5),
        E("CM2", "competence", "+ Dénominateur ≤ 60 ; produit d'un entier et d'une fraction ; deux tiers de 12 €.", c3, 9),
        E("6e", "competence", "+ Sens [[quotient]] : 3/4 est aussi le quart de 3 (« guide-âne ») ; fraction opérateur sur un nombre ; [[pourcentages]].", c3, 14),
        E("6e", "repere", "Automatismes : 1/4 = 0,25 ; 1/2 = 0,5 ; 3/4 = 0,75 ; 3/2 = 1,5.", c3, 15),
        E("6e", "exemple", "Mise en perspective : pourquoi une fraction a été appelée [[nombre rompu]], nombre cassé ou nombre coupé.", c3, 16),
    ),
    F("decimaux", "Nombres décimaux",
        E("CE1 CE2", "notion", "L'[[écriture à virgule]] est introduite par la [[monnaie]] (centimes au CE1), sans les mots dixième ou centième ; la virgule repère le chiffre des unités.", c2, 27),
        E("CE1", "exemple", "2 € et 5 centimes s'écrit 2,05 € ; 12 € c'est plus que 60 centimes bien que 12 soit plus petit que 60.", c2, 27),
        E("CE2", "competence", "+ Additions (période 2) et soustractions (période 4) posées de montants en euro.", c2, 30),
        E("CM1", "competence", "Réintroduction par les [[fractions décimales]] ; l'écriture à virgule est un [[codage conventionnel]] (35,78 = 35 + 7/10 + 8/100) ; jusqu'aux centièmes ; [[partie entière]] et [[arrondi]].", c3, 6),
        E("CM2", "competence", "+ Jusqu'aux millièmes.", c3, 10),
        E("6e", "competence", "+ Multiplier deux décimaux (appui sur l'aire du rectangle) ; arrondi au dixième, au centième ; contrôle par un [[ordre de grandeur]].", c3, 13),
        E("6e", "exemple", "Mise en perspective : l'écriture des décimaux de Simon Stevin de Bruges.", c3, 14),
    ),
)

calcul = D("calcul", "Calcul",
    F("calcul-mental", "Calcul mental",
        E("CP CE1 CE2", "notion", "Trois types d'apprentissages : [[mémoriser des faits numériques]], utiliser la numération, maîtriser des [[procédures]] ; séances quotidiennes ; tests en temps limité mesurant la [[fluence]] (routines sans stress : écart filles-garçons relevé par Repères CM1 2023) ; écrits intermédiaires sur l'ardoise.", c2, 5),
        E("CP", "attendu", "Tables d'addition : 8 égalités à trou en une minute ; doubles et moitiés usuels ; procédures (ajouter 9, complément à la dizaine…) : 9 résultats en trois minutes.", c2, 6),
        E("CP", "exemple", "« 47 + 3 = 50 + 5 = 55 » est incorrect : le symbole « = » ne se place qu'entre deux termes égaux.", c2, 5),
        E("CE1", "attendu", "+ Tables d'addition : 12 égalités en une minute ; [[tables de multiplication]] : 8 ; procédures : 12 résultats en trois minutes.", c2, 14),
        E("CE1", "exemple", "Distributivité : « 13 fois 7, c'est 10 fois 7 plus 3 fois 7 » ; multiplier par 10 avec un [[glisse-nombres]].", c2, 16),
        E("CE2", "attendu", "+ Tables d'addition : 15 égalités en une minute ; multiplication : 12 ; procédures : 15 résultats en trois minutes ; multiplier par 4 ou 8 (doubles successifs).", c2, 22),
        E("CM1 CM2", "competence", "Mêmes trois types d'apprentissages ; faits numériques sur fractions et décimaux (écriture décimale de fractions usuelles) ; multiplier et diviser un décimal par 10, 100, 1 000 ; multiplier par 5 ; [[distributivité]] dans des cas simples.", c3, 7),
        E("6e", "competence", "Automatismes : multiplier et diviser un décimal par 10, 100, 1 000 ; par 0,1, 0,01, 0,001.", c3, 13),
    ),
    F("operations", "Les quatre opérations",
        E("CP CE1 CE2", "notion", "Les opérations prennent leur sens dans la résolution de problèmes ; « [[La calculatrice n'est pas utilisée au cycle 2]] » (sauf besoins particuliers).", c2, 5),
        E("CP", "competence", "Sens de l'addition et de la soustraction (opération inverse) ; addition posée seulement en période 4 ou 5 ; sens de la multiplication (« fois », additions itérées).", c2, 5),
        E("CE1", "competence", "+ Soustraction posée au plus tard en période 3 : [[un unique et même algorithme]] privilégié dans l'école du CE1 au CM2 (« par cassage » ou « par compensation ») ; symbole « × » ; [[commutativité]] ; [[parité]].", c2, 13),
        E("CE1", "exemple", "Le potager de huit colonnes de quatre salades : 8 × 4 = 4 × 8.", c2, 13),
        E("CE2", "competence", "+ Multiplication posée au plus tard en période 4 ; sens de la division (symbole « ÷ ») ; « terme », « somme », « différence », « facteur », « produit », « multiple ».", c2, 21),
        E("CM1", "competence", "+ Estimer un résultat ; parenthèses ; additionner et soustraire des décimaux ; [[division euclidienne]] avec un diviseur à un chiffre.", c3, 7),
        E("CM2", "competence", "+ Multiplier un décimal par un entier ; [[divisions décimales]] (diviseur à un chiffre).", c3, 11),
        E("6e", "competence", "+ Produit de deux décimaux ; division euclidienne par un nombre < 100 ; sens [[partition]] et [[quotition]] de la division.", c3, 13),
        E("CM1 CM2 6e", "notion", "Au cycle 3, pas de calculatrice « au quotidien » ; au cours moyen, pas de calculatrice personnelle, mais l'enseignant peut en fournir.", c3, 3),
        E("6e", "exemple", "Mises en perspective : multiplication par jalousies, bouliers, numération sexagésimale babylonienne.", c3, 14),
    ),
)

problemes = D("problemes", "Résolution de problèmes et algèbre",
    F("resolution", "Résoudre des problèmes",
        E("PS MS GS", "notion", "Problèmes arithmétiques en une seule étape : réunion, ajout et retrait ([[problèmes de parties-tout]]), comparaison, groupements ou partage, déplacement ; du matériel figuratif au matériel symbolique puis au calcul mental ; séances fréquentes à partir du milieu de la maternelle.", c1, 44),
        E("PS", "competence", "Recherche du tout ou d'une partie en réalisant l'action avec du matériel figuratif.", c1, 45),
        E("MS", "competence", "+ Position finale sur une piste ; problèmes de groupements ; valeur d'une part dans un [[partage équitable]].", c1, 45),
        E("GS", "competence", "+ Quantité ajoutée ou retirée ; comparaison (écart) ; partage avec reste ; représentation sur papier.", c1, 46),
        E("GS", "crpe", "Dès 5 ans, proposer des problèmes dont l'énoncé est en [[discordance]] avec l'opération : « Pierre a cinq billes. Il a trois billes de moins que Julie. Combien Julie a-t-elle de billes ? »", "", None),
        E("CP CE1 CE2", "notion", "Enseignement explicite fondé sur le [[modèle de résolution de problèmes en quatre phases]] : comprendre (reformuler « l'histoire »), [[modéliser]], [[calculer]], [[répondre]], avec [[régulation]] ; [[au moins dix problèmes par semaine]] ; proposer des énoncés dont les termes n'induisent pas l'opération (« plus » pour une soustraction) ; [[institutionnalisation]].", c2, 8),
        E("CP", "competence", "Problèmes additifs en une étape de type [[parties-tout]] (la transformation est traitée comme un parties-tout) ; additifs en deux étapes et multiplicatifs (champ ≤ 30), dont le partage équitable.", c2, 9),
        E("CP", "exemple", "« Anna avait 43 cerises. Elle en a mangé 18 » : barres de dix cubes, on « casse » une dizaine.", c2, 9),
        E("CE1", "competence", "+ [[Comparaison]] additive ; [[schéma en barre]], schéma avec déplacement sur un axe ; problèmes mixtes en deux étapes.", c2, 17),
        E("CE1", "exemple", "« Léo a 188 billes. Lucie en a 75 de plus que Léo » : schéma à deux barres.", c2, 17),
        E("CE2", "competence", "+ [[Comparaison multiplicative]] (« fois plus » ≠ « de plus ») ; [[produits cartésiens]] (tableau, arbre) ; mixtes en deux ou trois étapes ; [[problèmes atypiques]] sur un champ < 100.", c2, 23),
        E("CE2", "exemple", "Poupée avec trois pantalons et sept teeshirts : 21 façons (tableau) ; clown : 12 costumes (arbre).", c2, 24),
        E("CM1 CM2 6e", "notion", "La résolution de problèmes [[occupe une place centrale]] et constitue le critère principal pour évaluer ; six compétences : [[chercher, modéliser, représenter, calculer, raisonner, communiquer]] ; régulation par la vraisemblance.", c3, 2),
        E("CM1", "competence", "+ Additifs en deux ou trois étapes ; [[problèmes de dénombrement]] ; [[problèmes d'optimisation]].", c3, 8),
        E("CM1", "exemple", "« 4,5 m pour la longueur d'une voiture, est-ce que cela est plausible ? »", c3, 8),
        E("CM2", "competence", "+ Problèmes [[préparant à l'utilisation d'algorithmes]].", c3, 11),
    ),
    F("algebre", "Algèbre : pensée algébrique",
        E("CM1 CM2 6e", "notion", "À partir du cycle 3, [[changement de paradigme]] : raisonner sur des nombres inconnus (lettres formelles au cycle 4) ; [[modèles pré-algébriques]] : schémas en barre, balances, [[motifs évolutifs]] ; le signe « = » relie deux expressions égales (« 178 – … = 6 × 8 »).", c3, 3),
        E("CM1", "competence", "Égalités à trous ; valeur d'un nombre inconnu représenté par un symbole ; [[programme de calcul]] ; suites de nombres et de motifs.", c3, 8),
        E("CM1", "exemple", "Tee-shirts à 12 € avec 5 € de livraison : (N × 12) + 5.", c3, 9),
        E("CM2", "competence", "+ Produire un programme de calcul ; nombre d'éléments à une étape donnée d'une suite de motifs.", c3, 12),
        E("6e", "competence", "Utiliser des modèles pré-algébriques pour résoudre des problèmes algébriques ; identifier la structure d'un motif évolutif.", c3, 16),
    ),
    F("motifs", "Motifs organisés (maternelle)",
        E("PS MS GS", "notion", "Un [[motif]] = configuration d'éléments organisés selon des règles ; [[motifs répétitifs]] (AABBAABB) et motifs évolutifs (à partir de cinq ans seulement) ; varier la nature (gestuelle, visuelle, sonore) ; la traduction formelle n'est pas un attendu.", c1, 50),
        E("PS", "competence", "Mémoriser et reproduire un motif répétitif très simple (alternance).", c1, 50),
        E("MS", "competence", "+ Reconnaître un motif à ses régularités ; le décrire ; prolonger une amorce en verbalisant la règle.", c1, 51),
        E("GS", "competence", "+ Structure d'un motif évolutif ; transcrire un motif avec d'autres symboles, du sonore au visuel ; créer des motifs.", c1, 51),
    ),
)

grandeurs = D("grandeurs", "Grandeurs et mesures",
    F("longueurs", "Longueurs et périmètre",
        E("PS MS GS", "notion", "Comparaisons directes (perception, superposition, [[même origine]]) puis indirectes (bande témoin) ; attributs relatifs (long / court).", c1, 48),
        E("PS", "competence", "Comparer des objets selon leur longueur (très différentes, puis en les mettant à la même origine).", c1, 49),
        E("MS", "competence", "+ Classer et ordonner des objets rectilignes ; « plus long que », « plus court que ».", c1, 49),
        E("GS", "competence", "+ Comparer indirectement avec une [[bande témoin]] ; produire un objet de même longueur.", c1, 49),
        E("CP", "competence", "[[Report de longueur]] (ficelle, bandelette), étalon ; règle graduée ; m, cm ; 1 m = 100 cm ; longueurs de référence.", c2, 25),
        E("CE1", "competence", "+ km ; encadrer une longueur entre deux entiers de cm ; estimer.", c2, 27),
        E("CE2", "competence", "+ dm, mm ; conversions en s'appuyant sur les relations entre unités ; [[périmètre]] (report au compas, mesure) sans formule.", c2, 29),
        E("CM1", "competence", "+ Du millimètre au kilomètre ; périmètre d'un polygone ; pas de mémorisation de formules.", c3, 16),
        E("6e", "competence", "+ Formules du périmètre du carré, du rectangle et du [[périmètre du disque]] (proportionnel au diamètre).", c3, 19),
        E("CP CE1 CE2 CM1 CM2", "crpe", "Pas de [[tableaux de conversion]] au cycle 2 ni au cours moyen : « 3,5 mètres est égal à 350 centimètres car 1 mètre est égal à 100 centimètres ».", "", None),
    ),
    F("masses-contenances", "Masses et contenances",
        E("MS", "competence", "Masse (introduite à partir de quatre ans) : soupeser, [[balance de type Roberval]] ; différencier masse et volume.", c1, 49),
        E("GS", "competence", "+ Ordonner trois masses ; réaliser l'équilibre ; [[transitivité]].", c1, 49),
        E("CP", "competence", "Comparer des masses en soupesant, balance Roberval (lourd, léger).", c2, 26),
        E("CE1", "competence", "+ g, kg ; 1 kg = 1 000 g ; masses de référence.", c2, 27),
        E("CE2", "competence", "+ Tonne ; [[contenances]] : L, dL, cL (1 L = 10 dL = 100 cL).", c2, 30),
        E("CM1", "competence", "+ Masses du milligramme à la tonne ; contenances du millilitre à l'hectolitre.", c3, 16),
        E("PS MS GS CP CE1 CE2", "crpe", "La masse est « [[confondue à tort avec le poids]] » dans le langage courant.", "", None),
    ),
    F("aires-volumes", "Aires, angles et volumes",
        E("CM1", "competence", "[[Aire]] introduite au CM1 : comparer sans mesurer, puis quadrillage, cm² ; angles : comparer, lexique et notations ; uniquement des [[angles saillants]] au cours moyen.", c3, 17),
        E("CM2", "competence", "+ cm², dm², m² et conversions ; aire du carré et du rectangle ; [[degré]] : l'angle droit mesure 90° ; construire la moitié d'un angle par pliage ; pas de [[rapporteur]] (introduit au collège).", c3, 18),
        E("6e", "competence", "+ Formules d'aire ; [[centimètre cube]] et volumes ; mesurer un angle.", c3, 19),
    ),
    F("temps-monnaie", "Durées et monnaie",
        E("CP", "competence", "Monnaie (période 2 ou 3) : euros entiers ≤ 100, rendre la monnaie ; lire les [[heures entières]].", c2, 26),
        E("CE1", "competence", "+ Centimes (période 2) et écriture à virgule (période 3) ; demi-heure, quart d'heure ; h et min.", c2, 28),
        E("CE2", "competence", "+ Durées en heures et minutes sur un axe chronologique ; problèmes à une ou deux étapes.", c2, 31),
        E("CE2", "exemple", "Rendre la monnaie sur 5 € pour 3,68 € par ajouts successifs.", c2, 30),
        E("CM2", "competence", "+ Secondes : [[système sexagésimal]].", c3, 18),
        E("6e", "competence", "+ Conversions de durées ; jours dans une année bissextile, siècle, millénaire.", c3, 19),
        E("6e", "exemple", "Mises en perspective : calendriers julien et grégorien ; [[clepsydres]].", c3, 20),
    ),
)

geometrie = D("geometrie", "Espace et géométrie",
    F("solides", "Solides",
        E("PS MS GS", "notion", "Reconnaître et décrire plutôt que nommer ; empreintes des faces planes ; pas de représentation en perspective en maternelle ; distinguer [[tri]] (un critère, deux groupes) et [[classement]].", c1, 47),
        E("MS", "competence", "Reconnaître et classer cube, boule, pyramide à base carrée, cylindre ; reproduire un assemblage de cinq solides.", c1, 48),
        E("GS", "competence", "+ Décrire cube, pavé, boule, pyramides, cylindre, cône (nombre de faces).", c1, 48),
        E("CP", "competence", "Cube, boule, cône, cylindre, [[pavé]] ; « face » ; au CP le cube « n'est pas considéré comme un pavé ».", c2, 31),
        E("CE1", "competence", "+ Pyramide ; « face », « sommet » et « arête » ; dénombrer faces, arêtes, sommets d'un [[polyèdre]].", c2, 33),
        E("CE2", "competence", "+ Représentations en perspective (lecture) ; [[patron]] d'un cube.", c2, 35),
        E("CM1", "competence", "+ [[Prisme droit]] ; construire un patron du cube.", c3, 21),
        E("CM2", "competence", "+ Reconnaître un patron du pavé.", c3, 22),
        E("6e", "competence", "Vision dans l'espace : [[assemblages de cubes]].", c3, 23),
    ),
    F("figures", "Figures planes et constructions",
        E("PS MS GS", "notion", "L'enseignant emploie le lexique exact (« disque » et non « rond », « sommet » et non « pointe ») ; varier les orientations des figures.", c1, 36),
        E("MS", "competence", "Reconnaître triangle, carré, disque ; reproduire un assemblage (puzzle, pavage).", c1, 48),
        E("GS", "competence", "+ Décrire et nommer carré, rectangle, triangle, disque dans toutes les orientations ; utiliser la [[règle]] pour tracer.", c1, 48),
        E("CP", "competence", "Disque, carré, rectangle, triangle ; « sommet », « côté » ; [[alignements]] ; tracer à la règle.", c2, 32),
        E("CE1", "competence", "+ Cercle, triangle rectangle ; [[angle droit]], angle aigu, angle obtus ; [[équerre]] ; [[compas]] ; milieu (par pliage) ; code de l'angle droit.", c2, 34),
        E("CE2", "competence", "+ Losange, polygone, quadrilatère ; rayon, diamètre, diagonale ; [[axes de symétrie]] (pliage, calque) ; compléter une figure symétrique.", c2, 36),
        E("CM1", "competence", "+ [[Perpendicularité]], [[parallélisme]] ; triangles isocèle, équilatéral ; cercle comme ensemble de points ; symétrique sur quadrillage.", c3, 20),
        E("CM2", "competence", "+ Trapèze, pentagone, hexagone ; [[programme de construction]] ; symétrique par rapport à une diagonale du quadrillage.", c3, 21),
        E("6e", "competence", "+ [[Médiatrice]], [[bissectrice]] ; somme des angles d'un triangle ; [[cercle circonscrit]] ; symétrique d'un point ; premières preuves, [[pensée déductive]].", c3, 22),
        E("CM1 CM2", "crpe", "Notations [AB], (AB), [AB) utilisées par l'enseignant mais non exigibles : on écrit « tracer le segment [AB] ».", "", None),
    ),
    F("reperage", "Repérage et déplacements",
        E("CP", "competence", "Vocabulaire des positions relatives ; plan de la classe ; coder un déplacement ; robot : au maximum dix instructions, dont deux virages.", c2, 32),
        E("CE1", "competence", "+ Plan de l'école, photo aérienne ; robot : quinze instructions, dont quatre virages.", c2, 34),
        E("CM1 CM2", "competence", "Vocabulaire des déplacements ; suite d'instructions ; assemblages de cubes.", c3, 21),
    ),
)

donnees = D("donnees", "Données, probabilités, proportionnalité",
    F("donnees", "Organisation et gestion de données",
        E("CP", "competence", "Enquête : caractère qualitatif (deux à cinq valeurs) ; tableau ; [[diagramme en barres]].", c2, 37),
        E("CE1 CE2", "competence", "Lire et interpréter tableaux et diagrammes ; au CE2, caractères quantitatifs discrets.", c2, 38),
        E("CM1", "competence", "+ Courbe, points dans un repère ; données réelles (changement climatique, biodiversité).", c3, 24),
        E("CM2", "competence", "+ [[Diagramme circulaire]].", c3, 25),
        E("6e", "competence", "+ Mener une [[enquête statistique]] ; filtrer des données.", c3, 25),
    ),
    F("probabilites", "Probabilités (cycle 3)",
        E("CM1", "competence", "[[Expériences aléatoires]] ; « impossible », « possible », « certain », « probable », « peu probable », « une chance sur deux » ; [[équiprobabilité]] ; deux issues ne signifient pas une chance sur deux.", c3, 24),
        E("CM2", "competence", "+ « [[a chances sur b]] » ; notion d'[[indépendance]] (le dé « ne se souvient pas ») ; tableau ou arbre.", c3, 25),
        E("6e", "competence", "+ Probabilité = nombre entre 0 et 1 ; [[approche fréquentiste]].", c3, 26),
    ),
    F("proportionnalite", "Proportionnalité (cycle 3)",
        E("CM1 CM2", "notion", "Raisonnements en langage naturel fondés sur la [[linéarité]] ; problèmes uniquement dans le cadre des grandeurs ; [[pas de tableaux de proportionnalité]] au cours moyen ; ni coefficient ni « [[produit en croix]] ».", c3, 26),
        E("CM1", "exemple", "« 4 pains aux raisins coûtent 7 €. Quel est le prix de 12 pains aux raisins ? » : inutile de calculer le prix unitaire.", c3, 26),
        E("6e", "competence", "+ Définition ; [[retour à l'unité]] ; tableau autorisé ; échelles ; le produit en croix n'est pas enseigné.", c3, 27),
    ),
    F("informatique", "Initiation à la pensée informatique",
        E("CP CE1", "competence", "Coder des déplacements (robot sur un tapis quadrillé) ; algorithmes des opérations posées ; poursuivre une [[suite évolutive]] dès le CE1.", c2, 32),
        E("CM1 CM2", "competence", "Codages de déplacements élargis ; programmes de calcul ; programmes de construction ; [[Scratch]], tableur.", c3, 28),
        E("6e", "competence", "Instruction, séquence d'instructions, entrées, sorties, [[répétitions]].", c3, 28),
    ),
)

ecrire({
    "id": "maths",
    "nom": "Mathématiques",
    "nomMaternelle": "L'acquisition des premiers outils mathématiques",
    "intentions": "Maternelle : fréquentation quotidienne des mathématiques ; quatre modalités (jeu, résolution de problèmes concrets, entraînement, mémorisation) auxquelles s'intègre la [[manipulation]], toujours [[verbalisée]]. Cycle 2 : du [[concret à l'abstrait]], en passant par la [[représentation imagée]] ; priorité à la numération, au calcul et à la résolution de problèmes arithmétiques ([[les deux tiers]] du temps au minimum) ; aborder d'emblée le programme de la classe, sans séquence de révision pour tous. Cycle 3 : la résolution de problèmes au centre ; [[automatismes]] ; initiation à la [[pensée algébrique]] et à la [[pensée informatique]] ; égalité filles-garçons (valoriser des mathématiciennes).",
    "domaines": [nombres, calcul, problemes, grandeurs, geometrie, donnees],
})
