"""Sciences et technologie PS→6e, programmes applicables en 2026-27 :
PS-GS : c1-2026 (« Découvrir le monde du vivant, de la matière et des objets ») ; CP : sci-c2-2026 (OCR) ;
CE1-CE2 : qlm-vmo-2020 ; CM1 : sci-c3-2026 (OCR) ; CM2-6e : sci-c3-2023 (« fin de cours moyen » → CM2, « fin de sixième » → 6e).
Repères d'âge du C1 : « avant 4 ans » → PS, « à partir de 4 ans » → MS, « à partir de 5 ans » → GS."""
from commun import E, S, F, D, ecrire

c1, cp, qlm, cm1, old = "c1-2026", "sci-c2-2026", "qlm-vmo-2020", "sci-c3-2026", "sci-c3-2023"

demarches = D("demarches", "Démarches scientifiques et technologiques",
    F("demarche", "Démarche scientifique",
        E("PS MS GS", "notion", "Dépasser les représentations spontanées par l'[[observation]], la [[manipulation]], l'[[expérimentation]] et les activités langagières ; décrire ce que je fais et ce qui se passe ; alterner exploration libre et temps dirigés ; ouvrages documentaires.", c1, 59),
        E("CP", "notion", "Première approche des démarches scientifique et technologique ; « les démarches scientifiques donnent la primauté aux faits » ; notions de [[reproductibilité]] et de [[robustesse]] d'une expérience ; [[variabilité des mesures]] ; programmes structurés en quatre domaines ; démarches et activités « ouvertes et non prescriptives ».", cp, 1),
        E("CE1 CE2", "competence", "Pratiquer, avec l'aide des professeurs, quelques moments d'une [[démarche d'investigation]] : questionnement, observation, expérience, description, raisonnement, conclusion.", qlm, 49),
        E("CM1", "notion", "+ Identifier un problème scientifique, formuler des hypothèses mises à l'épreuve du réel ; prendre en compte les [[conceptions initiales]] ; modélisation ; démarche technologique en projet.", cm1, 1),
        E("CM2 6e", "competence", "Pratiquer des démarches scientifiques et technologiques ; concevoir, créer, réaliser ; faire preuve d'[[esprit critique]] : distinguer ce qui relève d'une croyance de ce qui constitue un savoir scientifique.", old, 80),
        E("CP", "crpe", "Égalité filles-garçons : la répartition des tâches dans le groupe « ne soit pas fixe », pour que chaque élève puisse manipuler et rédiger.", "", None),
    ),
)

matiere = D("matiere", "La matière",
    F("etats", "États de la matière et mélanges",
        E("PS", "competence", "Explorer solides et liquides (transvasements) ; effets d'un déplacement d'air ; réaliser des mélanges ; observer la fusion et la solidification de l'eau.", c1, 63),
        E("MS", "competence", "+ Condition favorable à la fusion de la glace ; mettre en évidence la présence d'[[air]] ; solides qui se dissolvent ou non dans l'eau.", c1, 63),
        E("GS", "competence", "+ Nommer l'état de l'eau (pluie, neige, givre…) ; récupérer à l'aide d'un filtre les solides non dissous.", c1, 63),
        E("CP", "competence", "Reconnaître et identifier les états solides et liquides de l'eau dans les phénomènes naturels ; comparer des masses (balance de Roberval) ; lire la température (thermomètre, [[degré Celsius]]).", cp, 3),
        E("CE1 CE2", "attendu", "[[Identifier les trois états de la matière et observer des changements d’états]] (solidification, condensation, fusion) ; états de l'eau ; matérialité et compressibilité de l'air.", qlm, 49),
        E("CE2", "repere", "« Tout ce qui est lié à l’état gazeux est abordé en CE2. »", qlm, 49),
        E("CM1", "competence", "Masse et volume : mesurer avec une balance, [[tare]] ; [[mélanges homogènes]] et mélanges [[hétérogènes]] ; séparer par [[tamisage]], [[décantation]], [[filtration]] ; [[saturation]].", cm1, 3),
        E("CM1", "exemple", "Trouver la quantité maximale de sel dissoute dans un volume d'eau, et comparer aux autres groupes pour tester la reproductibilité.", cm1, 4),
        E("CM2", "competence", "Décrire un échantillon de matière (masse, volume) ; diversité de la matière et de ses transformations à l'échelle macroscopique ; classer les matériaux selon leurs propriétés.", old, 81),
        E("6e", "competence", "+ Relation de proportionnalité entre masse et volume (prépare la [[masse volumique]] au cycle 4) ; séparation par évaporation.", old, 81),
    ),
    F("mouvement-energie", "Mouvements, énergie, signaux",
        E("CM1", "competence", "Mesurer une distance et une durée lors d'un déplacement ; lumière : matériaux [[transparents]], [[opaques]], [[translucides]] ; [[ombre propre]] et [[ombre portée]] ; phases de la Lune.", cm1, 5),
        E("CM2", "competence", "Décrire un mouvement en précisant le point de vue ; mouvement rectiligne ou circulaire ; conversions d'énergie ; circuits électriques à une boucle ; signaux et information.", old, 84),
        E("6e", "competence", "+ Calculer la vitesse (mouvement uniforme) ; formes d'énergie ; ombres dans le système Soleil-Terre-Lune.", old, 84),
    ),
)

vivant = D("vivant", "Le vivant et son environnement",
    F("diversite", "Diversité du vivant et classification",
        E("PS", "competence", "Nommer les caractéristiques morphologiques des animaux et des plantes ; mâle, femelle, jeune, adulte ; soins aux élevages et cultures.", c1, 60),
        E("MS", "competence", "+ Modes de déplacement en relation avec le milieu de vie ; respecter la vie sous toutes ses formes.", c1, 60),
        E("GS", "competence", "+ Classer des animaux selon leurs caractéristiques (poils, plumes, écailles).", c1, 60),
        E("CP", "competence", "Caractériser ce qui est [[vivant, non vivant ou élaboré par des êtres vivants]] (critères : mobilité, croissance, reproduction, alimentation, perception).", cp, 5),
        E("CE1 CE2", "competence", "Identifier ce qui est animal, végétal, minéral ou élaboré par des êtres vivants ; régimes alimentaires ; besoins vitaux des végétaux.", qlm, 50),
        E("CM1", "competence", "Définir une [[espèce]] comme un ensemble d'individus [[interféconds]] ; [[classification en groupes emboîtés]] et liens de parenté ; [[clé de détermination]].", cm1, 10),
        E("CM2", "competence", "Caractériser l'unité et la diversité du vivant ; classer les organismes ; niveaux d'organisation (organisme, appareil, organe).", old, 87),
        E("6e", "competence", "+ La [[cellule]] (observations microscopiques) ; lire des arbres de parenté.", old, 87),
        E("CM1 CM2 6e", "crpe", "La classification (liens de parenté, groupes emboîtés) est distincte de l'identification à l'aide de [[clés de détermination]].", "", None),
    ),
    F("cycle-de-vie", "Cycle de vie, reproduction, développement",
        E("MS", "competence", "Reconnaître des étapes d'un cycle de vie ; besoins essentiels des animaux et végétaux ; animaux qui pondent des œufs, qui portent leur petit.", c1, 60),
        E("GS", "competence", "+ Nommer et ordonner les étapes du cycle de vie (germination, larve, nymphe, [[métamorphose]]) ; potager.", c1, 60),
        E("CE1 CE2", "competence", "Développement d'animaux et de végétaux ; [[le cycle de vie des êtres vivants]].", qlm, 50),
        E("CM1", "competence", "Étapes du développement des animaux de la [[fécondation]] à la naissance ; fécondation interne ou externe, [[ovipare]] et [[vivipare]].", cm1, 11),
        E("CM2 6e", "attendu", "[[Décrire le cycle de vie d’une plante à fleurs et celui d’un animal]].", old, 90),
    ),
    F("ecosystemes", "Environnement et écosystèmes",
        E("PS MS GS", "competence", "Découvrir le vivant dans un milieu proche ; contribuer à une action collective favorable à la [[biodiversité]] (GS).", c1, 60),
        E("CP", "competence", "Observer et décrire son environnement proche (êtres vivants, milieu de vie) ; agir pour protéger l'environnement ; développer un [[rapport sensible à la nature]].", cp, 5),
        E("CE1 CE2", "competence", "Interactions des êtres vivants entre eux et avec leur milieu ; relations alimentaires ; [[chaînes de prédation]].", qlm, 50),
        E("CM1", "competence", "[[Écosystème]] : ensemble d'êtres vivants, leur milieu de vie et leurs relations ; [[réseaux alimentaires]] ; besoins des végétaux et production de matière organique ; conséquences d'une action humaine (espèces invasives).", cm1, 11),
        E("CM2 6e", "competence", "Décrire un écosystème ; interdépendance dans un réseau trophique ; conséquences d'une action humaine.", old, 97),
    ),
    F("terre", "La Terre, planète active",
        E("CM1", "competence", "[[Météorologie]] : mesures (thermomètre, pluviomètre, anémomètre) ; distinguer météorologie et [[climat]] (première approche via un climat local) ; un exemple de [[risque naturel]].", cm1, 12),
        E("CM2", "competence", "Situer la Terre dans le système solaire ; activité de la planète Terre et ses conséquences.", old, 96),
        E("6e", "competence", "+ Conditions de la vie terrestre ; argumentation scientifique sur le réchauffement climatique actuel.", old, 96),
    ),
)

corps = D("corps", "Le corps humain et la santé",
    F("corps-mouvement", "Corps, sens et mouvement",
        E("PS", "competence", "Nommer quelques parties du corps ; découvrir les sens par des expériences sensorielles.", c1, 60),
        E("MS", "competence", "+ Organes sensoriels et modalités de perception ; changements liés à sa croissance.", c1, 61),
        E("GS", "competence", "+ Articulations et segmentation des membres ; se représenter avec un corps articulé.", c1, 61),
        E("CP", "competence", "Schéma corporel ; principales [[articulations]] et quelques os ; mouvements de rotation et de flexion/extension.", cp, 8),
        E("CE1 CE2", "competence", "Éléments permettant un mouvement corporel ; mesurer la croissance (taille, masse, pointure) ; dentition.", qlm, 50),
        E("CM1", "competence", "Le [[cerveau]] : perception, commande motrice, langage, mémorisation, émotions ; illusions sensorielles ; stratégies d'attention (mémoire à court et long terme).", cm1, 14),
    ),
    F("hygiene", "Alimentation et hygiène de vie",
        E("PS MS GS", "competence", "Règles d'[[hygiène]] (se laver les mains, se moucher) ; première approche nutritionnelle et éducation au goût ; lien avec l'EVAR.", c1, 61),
        E("CP", "competence", "Catégories d'aliments et leur origine ; rythme d'activité quotidien ; règles d'hygiène de vie (sommeil, variété alimentaire, activité physique, [[temps d'écran]]).", cp, 8),
        E("CE1 CE2", "competence", "Catégories d'aliments ; [[équilibre alimentaire]] (repas, journée, semaine) ; effets de l'activité physique ; besoins en sommeil.", qlm, 50),
        E("CM2", "competence", "Rôle des aliments pour le fonctionnement de l'organisme ; besoin de matière pour la croissance.", old, 89),
        E("6e", "competence", "+ Transformer et conserver les aliments ; [[microorganismes]].", old, 89),
        E("CP", "crpe", "Aborder l'éducation à la santé avec une approche positive et bienveillante, sans stigmatiser ni culpabiliser.", "", None),
    ),
    F("puberte", "Puberté et reproduction humaine",
        E("CM1", "competence", "Changements morphologiques à la [[puberté]] (courbes de croissance) ; âges différents selon les individus ; caractères sexuels primaires et secondaires ; en complément des séances d'EVAR, sans s'y substituer.", cm1, 15),
        E("CM2 6e", "attendu", "[[Décrire les changements pubertaires]] associés à la capacité de se reproduire ; distinguer la dimension biologique de la sexualité de ses autres dimensions.", old, 90),
    ),
)

objets = D("objets", "Les objets techniques",
    F("objets", "Objets, matériaux et besoins",
        E("PS", "competence", "Reconnaître et comparer des matériaux usuels ; utiliser des objets, connaître leur fonction ; fabriquer librement ou pas à pas.", c1, 62),
        E("MS", "competence", "+ Propriétés des matériaux ([[magnétisme]], transparence) ; différencier un objet du matériau qui le constitue ; trier les déchets.", c1, 62),
        E("GS", "competence", "+ Associer une solution technique à une fonction ; [[flottabilité]] (objets pleins d'une même matière) ; suivre une fiche technique ; 3 à 5 instructions pour conduire un robot.", c1, 62),
        E("CP", "competence", "Un [[objet technique]] est obtenu par intervention des êtres humains ; il répond à un besoin.", cp, 10),
        E("CE1 CE2", "competence", "[[Comprendre la fonction et le fonctionnement d’objets fabriqués]] ; circuits électriques simples ; bons conducteurs et isolants ; interrupteur ; règles de sécurité ; traitement de texte.", qlm, 51),
        E("CM1", "competence", "Évolution d'un objet selon les contextes ; fonctions des composants ; associer [[solutions technologiques]] et [[fonctions techniques]] ; croquis ; programmation d'objets techniques.", cm1, 16),
        E("CM2", "competence", "Distinguer besoins, fonctions techniques et solutions technologiques ; [[démarche technologique]] en projet ; [[cycle de vie]] d'un objet ; chaîne d'information et chaîne d'action d'un objet programmable.", old, 91),
    ),
)

ecrire({
    "id": "sciences",
    "nom": "Sciences et technologie",
    "nomMaternelle": "Découvrir le monde du vivant, de la matière et des objets",
    "intentions": "Maternelle : dépasser les représentations spontanées par l'observation, la manipulation, l'expérimentation et le langage. Cycle 2 : premières démarches scientifique et technologique, dans quatre domaines : la matière, les mesures, l'électricité ; le corps humain et la santé ; les êtres vivants dans leur environnement ; les objets techniques au cœur de la société (CP 2026 ; CE1-CE2 : « Questionner le monde du vivant, de la matière et des objets » 2020). Cycle 3 : conceptualisation, [[modélisation]], culture scientifique et technologique ; éducations transversales (santé, EVAR, [[développement durable]]).",
    "domaines": [demarches, matiere, vivant, corps, objets],
})
